theme = "awesome-identity"
baseURL = "https://jacob.parent.com"
title = "Will Mancuso"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


## Profile Configurations
[params.profile]
  portrait = "profile-picture.JPG"
  firstname = "Will"
  lastname = "Mancuso"
  title = "Electrical Engineering Student at LSU"
  bio = """I am a rising senior at LSU in Baton Rouge. I am an Electrical Engineering major and plan to graduate in the Spring of 2025. I hope that through my
time as a student at LSU I can become a part of making the school a better place, whether that be in a leadership role or representing the school
in Tiger Band.
 
  """

## Contacts Configurations
[params.contacts]
  email = "willdmancuso@gmail.com"
  instagram = "will_mancuso"
  linkedin = "will-mancuso-75aab1286"

[params.actions.resume]
  name = "See my Resume"
  url = "./Will-Mancuso-Resume-8-8-24.pdf"

## Footer Configurations
[params.footer]
  poweredBy = false
